name: Backend Deploymenty

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . -t johnstok815/mylittleu:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: johnstok815
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push the image to Docker Hubb
      run: docker push johnstok815/mylittleu

    - name: Pull the image to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull johnstok815/mylittleu:latest
          sudo docker stop mylittleu || true
          sudo docker rm mylittleu || true
          sudo docker run -d -p 8088:8081 --name mylittleu johnstok815/mylittleu:latest